import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import SideNav from '@/app/_components/sidenav/sidenav';
import GoogleRecaptchaWrapper from '@/app/_components/google-recaptcha-wrapper/goole-recaptcha-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'jacquietattoos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleRecaptchaWrapper>
          <div className="flex min-h-screen flex-col md:flex-row">
            <div className="w-full flex-none bg-summer-green text-white md:w-56 md:px-10 md:pt-5">
              <SideNav />
            </div>
            <div className="flex-grow p-0">{children}</div>
          </div>
          <div id="modal-root"></div>
        </GoogleRecaptchaWrapper>
      </body>
    </html>
  );
}
